import type { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Banner } from '../components/banner/Banner'
import { Card } from '../components/card/Card'
import { Divider } from '../components/divider/Divider'
import { Jobs } from '../components/jobs/Jobs'
import { MediaHorizontal } from '../components/media-horizontal/MediaHorizontal'
import { Typography } from '../components/typography/Typography'
import { api } from '../services/api'
import styles from '../styles/Home.module.scss'

type Localizacao = {
  bairro?: string
  cidade?: string
  pais?: string
}

type InfoJobs = {
  cargo: string
  ativa: boolean
  link: string
  localizacao?: Localizacao
}

interface IHomeProps {
  allJobs: InfoJobs[]
}

export default function Home({ allJobs }: IHomeProps) {
  return (
    <div>
      <Head>
        <title>Career page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <header>
          <Banner
            img="/img/foto-header.png"
            alt="Vagas"
            title="Trabalhe no Elo7"
          />
        </header>
        <div className={styles.container}>
          <Typography variant={'p'} className={styles.description}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
            convallis a urna dignissim interdum. Maecenas nec diam sit amet
            tortor porttitor accumsan. Morbi luctus orci eros, a molestie purus
            pharetra a. Morbi commodo feugiat vulputate. Maecenas vel tincidunt
            leo. Donec accumsan, mauris hendrerit sagittis finibus, purus felis
            iaculis ipsum, id maximus nulla nibh ac lectus.
          </Typography>
          <div className={styles.dividerInfo}>
            <Divider className={styles.line} />
            <a href="#opportunity">
              Vagas em aberto <span>&#xbb;</span>
            </a>
          </div>
        </div>
        <section className={styles.info}>
          <MediaHorizontal
            imgUrl="/img/placeholder-video.png"
            alt="video"
            title="Palavra do Ceo"
            subtitle="Carlos Curioni"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
            convallis a urna dignissim interdum. Maecenas nec diam sit amet
            tortor porttitor accumsan. Morbi luctus orci eros, a molestie purus
            pharetra a. Morbi commodo feugiat vulputate. Maecenas vel tincidunt
            leo. Donec accumsan, mauris hendrerit sagittis finibus, purus felis
            iaculis ipsum, id maximus nulla nibh ac lectus."
          />
          <div className={styles.team}>
            <Typography variant="h3">
              Conheça nosso time <br />
              fora de série
            </Typography>
            <ul>
              <li>
                <Image
                  src={'/img/camila.png'}
                  height={'209'}
                  width={'200'}
                  alt="Camila"
                />
              </li>
              <li>
                <Image
                  src={'/img/guto.png'}
                  height={'209'}
                  width={'200'}
                  alt="Guto"
                />
              </li>
              <li>
                <Image
                  src={'/img/david.png'}
                  height={'209'}
                  width={'200'}
                  alt="David"
                />
              </li>
              <li>
                <Image
                  src={'/img/beatriz.png'}
                  height={'209'}
                  width={'200'}
                  alt="beatriz"
                />
              </li>
            </ul>
          </div>
        </section>
        <section className={styles.sectionCulture}>
          <div className={styles.culture}>
            <Card
              imageUrl="/img/qualidade.png"
              alt="Qualidade"
              title="Qualidade de vida"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
            convallis a urna dignissim interdum. Maecenas nec diam sit amet
            tortor porttitor accumsan. Morbi luctus orci eros, a molestie purus
            pharetra a. Morbi commodo feugiat vulputate."
            />
            <Card
              imageUrl="/img/descontracao.png"
              alt="Descontração"
              title="Ambiente Descontraído"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
            convallis a urna dignissim interdum. Maecenas nec diam sit amet
            tortor porttitor accumsan. Morbi luctus orci eros, a molestie purus
            pharetra a. Morbi commodo feugiat vulputate."
            />
            <Card
              imageUrl="/img/atividades.png"
              alt="Atividades"
              title="Atividades extras"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
            convallis a urna dignissim interdum. Maecenas nec diam sit amet
            tortor porttitor accumsan. Morbi luctus orci eros, a molestie purus
            pharetra a. Morbi commodo feugiat vulputate."
            />
          </div>

          <div className={styles.dividerInfo}>
            <Divider className={styles.line} />
            <a
              href="https://jobs.kenoby.com/elo7"
              target="_blank"
              rel="noreferrer"
            >
              Saiba mais<span> &#xbb;</span>
            </a>
          </div>
        </section>
        <section className={styles.sectionOpportunity}>
          <div className={styles.imageBottom}>
            <Image
              src={'/img/foto-bottom.png'}
              alt="foto-bottom"
              height={'300'}
              width={'860'}
              // height={'100%'}
              // width={'100%'}
              layout={'responsive'}
              objectFit={'contain'}
            />
          </div>
          <Typography className={styles.opportunity} variant="h4">
            Vagas em aberto
          </Typography>

          <div className={styles.containerOpportunity}>
            <Typography className={styles.opportunity} variant="h5">
              Desenvovimento
            </Typography>
            <ul id="opportunity">
              {allJobs.map((job, index) => {
                const local = job.localizacao
                  ? `${job.localizacao?.bairro} - ${job.localizacao?.cidade}, ${job.localizacao?.pais}`
                  : 'Remoto'
                const isActive = job.ativa

                if (isActive) {
                  return (
                    <li key={index}>
                      <Jobs
                        title={job.cargo}
                        link={job.link}
                        location={local}
                      />
                    </li>
                  )
                }
              })}
            </ul>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <Typography variant="p"> &copy; Elo7</Typography>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await api
    .get('vagas')
    .then((res) => res.data.vagas)
    .catch((err) => {
      console.log(err.message)
    })

  return {
    props: {
      allJobs: response
    },
    revalidate: 60 * 60 * 8
  }
}
